### PR TITLE
Use sensible fcontext default stack.

### PR DESCRIPTION
**Pull request by heiner**

### CODE REVIEW

**Comment by heiner** [comment]
The test failure on all Linuxes is related to https://github.com/septag/deboost.context/issues/4.

**Comment by condnsdmatters** [comment]
While the default stack method seems like a saner way to do things, is a resolution on this PR necessary?  I'd have thought unless we overflow again, probably not, but have not properly investigated this...  If so, shall I close and open an Issue?

**Comment by heiner** [comment]
Answer to your question heavily depends on your definition of "necessary".

**Comment by condnsdmatters** [comment]
lol i suppose so: i guess what i meant is - my understanding is that this PR aimed to use a default stack size instead of one arbititrarily chosen by us, but this is broken upstream. to my mind this PR is good practice but mainly cosmetic in that it shouldn't really affect most peoples running of NLE post pr #334 .  is there something i'm missing in the understanding of this issue that means NLE could break unexpectedly in future?

**Comment by heiner** [comment]
No you're right. It could break if the stack gets very large but is unlikely to at this point. We can close this PR for now.

**Pull request closed without merging**
