### PR TITLE
Deploy pip package and docker images on release

### PR DESCRIPTION
**Pull request by edran**
As per title, this PR should in theory allow us to automatise deployment of both the package and the docker images, upon _releasing_ a release (I know, I know...).

These changes were tested at https://github.com/edran/nle/tree/chore/build-and-push, with the pypi package being automatically uploaded to https://test.pypi.org/project/nle/ and the docker images to https://hub.docker.com/repository/docker/edran/nle and https://hub.docker.com/repository/docker/edran/nle-xenial.

If the tests pass (after we add the tokens to the repo),then we can make a new release.

### CODE REVIEW

**Comment by heiner** [comment]
Docker image test failure is expected for now?

Looks good otherwise.

Still waiting on the GH action secrets.

**Comment by edran** [comment]
Yes, the error is due to the token missing.

**Comment by edran** [comment]
Rerunning the workflows now.

**Comment by edran** [comment]
Closing this in favour of #34.

**Pull request closed without merging**
