### PR TITLE
Prevent use of macro __warn_unused_result__ for M1 Macs, fixing Issue…

### PR DESCRIPTION
**Pull request by condnsdmatters**
… #340.

### CODE REVIEW

**Review by samvelyan — APPROVED** [review]
Look good!

**Comment by condnsdmatters** [comment]
Think cherry-pick is the better way to do this.

**Review by heiner — APPROVED** [review]

**Comment by samvelyan** [comment]
I can confirm that now the following successfully installs `nle` on my M1 Chip Mac
```
pip install git+https://github.com/facebookresearch/nle.git@eric/M1-URWARN
```

**Comment by condnsdmatters** [comment]
I found the cherry-pick didnt seem to work on Mika's macbook, so reverted the change. Will investigate on my M1, but might just merge this later.

**Comment by heiner** [comment]
If so, this is a good opportunity to have your code in upstream NH :)

**Pull request merged**
