### PR TITLE
Make an easier import structure for nethack dataset.

### PR DESCRIPTION
**Pull request by condnsdmatters**

### CODE REVIEW

**Comment by condnsdmatters** [comment]
The idea is to be able to do simple 
```
import nle.dataset as nld
data = nld.TtyrecDataset("autoascend")
nld.add_nledata_directory(... )
```
instead of having a lot of imports

**Comment by minqi** [comment]
LGTM

**Comment by condnsdmatters** [comment]
Im sad that your review counts for nothing @minqi

**Review by tscmoo — APPROVED** [review]
Seems reasonable

**Pull request merged**
